source 'https://rubygems.org'

ruby '3.3.0'

gem 'rails', '~> 7.1.3', '>= 7.1.3.2'
gem 'pg', '~> 1.1'
gem 'puma', '>= 5.0'
gem 'tzinfo-data', platforms: %i[ windows jruby ]
gem 'bootsnap', require: false
gem 'jwt'
gem 'bcrypt'
gem 'rack-cors'

group :development, :test do
  gem 'debug', platforms: %i[ mri windows ]
end
