default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: dog-topia-dev

test:
  <<: *default
  database: dog-topia-test

production:
  <<: *default
  database: dog-topia-prod
